# rainbow-proxy – Squid configuration
# Generated by entrypoint.sh at container startup; do not edit directly.

# Accept proxy connections on 3128 with SSL-bump support.
http_port 3128 ssl-bump \
    cert=/etc/squid/ssl/ca.crt \
    key=/etc/squid/ssl/ca.key \
    generate-host-certificates=on \
    dynamic_cert_mem_cache_size=4MB

# Helper that generates a forged certificate for each bumped HTTPS host.
sslcrtd_program /usr/lib/squid/security_file_certgen \
    -s /var/cache/squid/ssl_db \
    -M 4MB
sslcrtd_children 5

# SSL-bump strategy:
#   step1 – peek at the Client Hello to read the SNI.
#   bump   – only intercept mapped domains (rewriter can then see the full URL).
#   splice – tunnel everything else unchanged (no forged cert, no interception).
acl step1 at_step SslBump1
__MAPPED_DOMAINS_ACL__
ssl_bump peek step1
ssl_bump bump mapped_domains
ssl_bump splice all

# URL rewriter.
url_rewrite_program /usr/local/bin/rewriter.py
url_rewrite_children 5 startup=1 idle=1
url_rewrite_concurrency 0

http_access allow all
cache deny all

access_log stdio:/dev/stdout
cache_log stdio:/dev/stderr

coredump_dir /var/cache/squid
